### ISSUE TITLE
[Bug] Arena features not working when less than 5 players are shown

### ISSUE THREAD

**Issue by s17Meliodas** [DinoDevs/GladiatusCrazyAddon#178]
**Describe the bug**
If there are not 5 opponents in the list, the feature stops working. Script also doesn't place opponents in level order. 

**Browser info (optional)**
 - OS: Windows 10
 - Browser Opera, although I'm pretty sure it applies on every browser and version.
 
![image](https://user-images.githubusercontent.com/39100448/84535142-d53d3000-acb0-11ea-986e-cbcf5f2f161f.png)
![image](https://user-images.githubusercontent.com/39100448/84535306-3107b900-acb1-11ea-83f7-5d9680935d1b.png)
![image](https://user-images.githubusercontent.com/39100448/84535343-42e95c00-acb1-11ea-89f2-13e1cd99546d.png)

**Comment by GreatApo** [comment]
Hello Gladiator! I had a look on the code and it should work irrelevant to the number of players. Are you on the developer version (4.2.1) or on 4.2.0? (you can see the version number at the bottom of the game)

**Comment by s17Meliodas** [comment]
I am on 4.2.0

**Comment by GreatApo** [comment]
I just had a look at version's 4.2.0 code and you are right the code there was expecting 5 players. It is also mentioned in the current progress file as fixed fixed in the developer version. It will be patched in next release.

If you want it fixed now you can install the developer version:
- Go to main GitHub page
- Click the green "clone or download" button and download a zip
- Disable your current addon version
- Follow the zip installation guide: https://github.com/DinoDevs/GladiatusCrazyAddon/blob/master/documentation/installation-opera.md#install-using-the-zip-extension-file
Mind that this method doesn't auto-update but you can revert to the old version just by disabling/enabling each addon.

**Comment by s17Meliodas** [comment]
Thank you!
I'll check it out.

**Comment by s17Meliodas** [comment]
It seems I cant install the developer version. Once I try to load the unpacked extension it says there was a problem where the manifest couldnt be readen. Also the unzip folder doenst look like in the guide, dont know if it matters.  I guess I can wait until next realease. If there is another way to get the developer version I'l like to try it tho.

**Comment by GramThanos** [comment]
Select the "source" folder inside the "gladiatus crazy addon" folder.

**Comment by s17Meliodas** [comment]
It worked. Thank you for everything. i'll be trying it
