### ISSUE TITLE
Auction sorting not working on mobile (Android)

### ISSUE THREAD

**Issue by ahoj1234** [DinoDevs/GladiatusCrazyAddon#229]
Auction sorting not sorting on click (e.g. sort by damage… descending, ascending…). Not working at all.

 - OS: Android 10
 - Browser: Yandex (latest) / Kiwi (latest)

**Comment by GramThanos** [comment]
Please check if the problem exists on the latest version too.

**Comment by ahoj1234** [comment]
yeah, does nothing on latest version as well. Maybe the mobile browser limitation is the problem itself… (on Windows PC platform it works fine).
Same with some other addon's scripts like with smeltery (sending all to packages).

**Comment by FrutyX** [comment]
There is this question, if we even should support this.

There are countless variables when it comes to phones (OS, browser etc etc...) and GCA was and is meant for modern computer browsers (with Windows, no clue about Linux and others...).

You could end up rewriting the whole just because some mobile browser does not support it, that's just... it does not make any sense.

**Comment by GramThanos** [comment]
It should work though. I don't think the problem is 100%  related to the mobile factor. So, it worths investigating into this one, but is is not a high priority.

**Comment by FrutyX** [comment]
@GramThanos I am telling ya, drop it.

You don't want to support cross-platform development, do you really think this is the only thing that is broken on an Android? I went to check it for myself, I could make list about "what is broken" on Android, I am seeing a lot of errors, funny enough, there is no error for this specific Issue, the auction sorting just doesn't react at all.

**Comment by GramThanos** [comment]
FYI, not mobile related.
