### ISSUE TITLE
Auction sorting not working

### ISSUE THREAD

**Issue by ahoj1234** [DinoDevs/GladiatusCrazyAddon#235]
**Describe the bug**
  If you open auction and try sorting by damage (highest to lowest) it seems like the script is sorting only 2 digits. Which is not wanted for weapons as weapons has also 3 digit damage status.

**Screenshots**
![image](https://user-images.githubusercontent.com/3464904/110830615-b13b6900-8299-11eb-89d2-df3480378a24.png)

**Comment by GramThanos** [comment]
Ok, I need to rescript this one and merge it with packages search too.

**Comment by FrutyX** [comment]
@GramThanos 

Uhh, I was just checking some bugs here, and I wanted to test this one, instead of that, I found completely something different, I am not sure if I have something wrong on my side, but I don't see any auction (filter) settings at all and I am also getting an console error:

**auction.js?4.3.5&built=1631143038779:543 Uncaught TypeError: Cannot set properties of null (setting 'level')
    at Object.initKeywordMap (auction.js?4.3.5&built=1631143038779:543)
    at Object.init (auction.js?4.3.5&built=1631143038779:456)
    at Object.inject (auction.js?4.3.5&built=1631143038779:32)
    at fireLoad (auction.js?4.3.5&built=1631143038779:828)**

![error](https://user-images.githubusercontent.com/23278552/132598197-608788bd-bb34-469a-96d1-c439796de8ee.PNG)

I've tried 4.3.4, no change. Tested this with clean GCA settings (default).

Chrome v95 (Canary) detected this error, meanwhile Chrome v93 is not showing any error, but I don't see the auction filter either, what a mess.

**Comment by FrutyX** [comment]
@GramThanos not sure if you would notice if I just edited my previous post, so sorry for spam.

I just tested it on Edge, and it works normally, no errors, Chrome, Chrome.... you naughty boy.

**Comment by FrutyX** [comment]
Is this a joke? Is there somewhere a hidden troll? 

It loaded normally now, so I have no clue, filter is visible and there is no error, perhaps it's under some specific circumstances?

Sorry for waking you up Gram, not sure what is this, I thought I found a bug, perhaps I did, but it's .... complicated.

**Comment by GramThanos** [comment]
Don't worry, I will test it tomorrow.
If I remember the code correctly the level read failed. I think this was not my code through :P

**Comment by FrutyX** [comment]
I was playing with my settings due to #262 and it seems this error goes away after you visit the auction page a few times, it's like addon is loading your profile, settings, Gladiatus or something.

I reset my settings again, and this error is back, after a few reloads, it's gone. So perhaps it's my fault that I test bugs when I have been testing GCA settings, but I leave it up to you, if you want to test it or rework so it will not occur, it is definitely connected to GCA settings and the way GCA reads Gladiatus.

**Comment by GramThanos** [comment]
This is also linked to #276

**Comment by GreatApo** [comment]
String sorting changed to number sorting, fixed #1a3feeb873abe848aa9508ff2dc695449fa8ed4c

**Comment by FrutyX** [comment]
Unless I am extremely lucky, I think yes, you did fixed it.

@GreatApo I found out that you are very good at fixing things (sorry Gram, maybe next time) 😃.
