### ISSUE TITLE
Integration with simulator to get percentages in arenas

### ISSUE THREAD

**Issue by MiguelSOliveira** [DinoDevs/GladiatusCrazyAddon#283]
Hi, first of all, great addon. I love it!

I'm not sure if this is even possible but since you guys have the data from the simulator, would it be possible to have the percentages in the arenas next to the gladiators names? This would decrease the amount of work of going from and to the simulator.

Here is what I mean:
<img width="338" alt="imagem" src="https://user-images.githubusercontent.com/8149533/139589019-0fb2d07a-a5c0-4381-a0ec-569f5cb835fa.png">

Thank you!

**Comment by FrutyX** [comment]
I ain´t no dev, but the simulator isn't integrated to Gladiatus, it's separated, this what you are proposing would require an integration and that's not all, it would have to check every single Gladiatus profile  and calculate the fight, that will create some server load for Gladiatus (reading profiles), but most importantly insane server load for the simulator server, because it would have to simulate the fight in the background, and this process for each player for multiple arena entries.

It might sound good on paper, but reality si completely different.

**Comment by GramThanos** [comment]
It was like that many years ago but GameForge asked us to remove this feature (and some others). Thus, we respected that and since then the simulator is just a page and not part of the addon.
