### ISSUE TITLE
Tr update

### ISSUE THREAD

**Issue by mattemre** [DinoDevs/GladiatusCrazyAddon#320]
**Turkish**
 - Language: (Türkçe)

[tr.txt](https://github.com/DinoDevs/GladiatusCrazyAddon/files/7795549/tr.txt)

**Comment by FrutyX** [comment]
I've added it, but there are two problems:

**First**, why did you changed 

`category_sound$cooldown_sound_notifications : "Sesli bildirimleri etkinleştir (Keşif, Zindan, Arena, Sirk Turma)",`

to this:

`category_sound$cooldown_sound_notifications : "Bekleme süresi ses bildirimlerini etkinleştir (Keşif, Zindan ,Arena)`

It's unfinished and Turma is missing, why would you delete that?

The **second** problem (I may need @GramThanos for this), you are using percentages in Turkish like this "%200" right? 

`category_market$custom_prices : "Virgülle ayrılmış özel piyasa fiyatları. Bir '%' ekleyerek öğenin fiyatının yüzdesine dayalı olarak hesaplayın. (ör. '10000, 10.000, %200')",`

and the problem is, that "%200" is not gonna work, it was made to be "200%", I think we can fix that, but that's Gram's script (#166), so waiting for him.

**Comment by GreatApo** [comment]
> **Turkish**
> 
> * Language: (Türkçe)
> 
> [tr.txt](https://github.com/DinoDevs/GladiatusCrazyAddon/files/7795549/tr.txt)

@mattemre Thank you very much for the updated translation! Do you think it would be a problem if we keep the percentages in this format: 100%?

**Comment by GramThanos** [comment]
I think gladiatus use the same number format everywhere (for example here in Greece 0.5 is normally written as 0,5, but the all the servers use 0.5) thus I would leave it as 100%. Otherwise we have also to change the view to %xx (not only the parser).

**Comment by FrutyX** [comment]
Alright, I've had a quick look on Turkish servers, they have percentages as Gram said, behind the number.

Changed the translation to "200%".

**Comment by mattemre** [comment]
[tr.txt](https://github.com/DinoDevs/GladiatusCrazyAddon/files/7797000/tr.txt)

i am realy sorry, my bad. I made 2 different saves. I sent you the wrong translation.

When we pronounce it as a percentage, we say it as a prefix. I wrote it as we said it.
