### ISSUE TITLE
Quick selection Important Rank - Guild Message

### ISSUE THREAD

**Issue by SleepingShadow-bit** [DinoDevs/GladiatusCrazyAddon#395]
In the case of important internal discussions via guild mails, which are only for the master and admins, a quick selection of the ranks (important rank - master / admin) would be very practical. 
 Currently you have to deselect and select 2 times.  The Quick Select should make that easier.

![IMG_20220803_220622](https://user-images.githubusercontent.com/8767665/182700613-05a9b8a4-a3ee-47e2-a521-d3fbff54b2d9.jpg)

**Comment by FrutyX** [comment]
I have implemented it.

Sadly, since I have a one-man-army guild, I was only testing this with my multiaccount, so I was very limited to properly test this. @SleepingShadow-bit you will have to do the testing with more members, technically, the members count or ranks shouldn't matter, but, you'll see.

**Comment by SleepingShadow-bit** [comment]
Admins and Masters have been selected.  sending works.  feature works.

**Comment by FrutyX** [comment]
Glad to hear it!

**Comment by FrutyX** [comment]
Implemented in v4.3.6, closing, re-open if needed.
