### ISSUE TITLE
Market features

### ISSUE THREAD

**Issue by DarkSide666** [DinoDevs/GladiatusCrazyAddon#42]
It would be very useful if you could add one small feature in mod=guildMarket and mod=market pages.

Description:
On double-click on item in your backpack drag-drop item in market sell area and focus+select all price field so user can instantly input price (1 gold most of the time) and click "Offer" button.

Also it would be great if there would be a way how to automatically set sell value to 1 gold. This would reduce time spent on repacking items using guild (or public) market.

**Comment by GreatApo** [comment]
So we have:
- Double click to drop in sell box (but can it be done technically?)
- Maybe we can add a toggle "1gold" button that will force prices to stay 1 gold

**Comment by DarkSide666** [comment]
yes exactly

**Comment by GramThanos** [comment]
The item move actions can not be scripted as the grag'n'drop handlers are inaccessible.
So, technically we would have to hack our way into getting access to the handlers which is very difficult... and it would be a mesh :P (hacking into the jQuery handlers and listeners and access the drag'n'drop object scopes).

I managed to access them a while back, but they made a small change and I had to hack it all again from the start.
Even if I manage to hack it again, it would be unstable and not a good approach.

That's why all item double-click features that involves item moving are not scripted for over a year now.

**Comment by DarkSide666** [comment]
hmmm..... then maybe some other idea how speed up item repacking process?
"1gold" toggle button would help too. Then there will be no need to touch keyboard in this process and all could be done by just using mouse.

**Comment by GreatApo** [comment]
maybe, no-refresh when selling? 😶

**Comment by DarkSide666** [comment]
hmmm - yeah, that would help too a bit. whole page refreshes are evil :)

**Comment by GreatApo** [comment]
Toggle button, when you click "1g" whatever you drop will have 1 gold price. The mode you are (auto or 1g) is the same after refresh.

![image](https://user-images.githubusercontent.com/9620510/34391291-521ae7ca-eb4d-11e7-9ee7-f72caad521ee.png)

commit cc07d3088e4349d9f9af4cd06ca0c02db72876c9

**Comment by DarkSide666** [comment]
You really ROCK !!! Thanks.
