### ISSUE TITLE
[Feature request] Sell all option

### ISSUE THREAD

**Issue by EconomicalDamage** [DinoDevs/GladiatusCrazyAddon#60]
Can you guys make like sell all option? or lets say sell ticked items in inventory or something that would make selling huge amounts of items not a pain in the ass :)

**Comment by GramThanos** [comment]
Even better we can create a script that plays the game for you.

**Comment by GreatApo** [comment]
There are technical issues with moving items, however, I'm going to leave this request open :)

**Comment by brunoaugusto** [comment]
The selling feature of the game is weird. There are two options that do have a 'Sell' option available, but one of them doesn't make much sense, well, at least not in English (sell all packages - but which packages? Gold?)

Then, 'Sell everything on this page'. With the add-on we have 15 items per page. If we want to sell 14 items and keep the 15th, we can't, because there's no such option.

It's a very nice feature GF killed by themselves

**Comment by GramThanos** [comment]
Double-click item sell scripted 3e032744ea9ee7be3ab123636dfbea84219012d9
